language: python
python::
  - "2.7"
  - "3.4"
  - "3.6.1"
services:
  - postgresql
before_script:
  - psql -c 'create database testdb;' -U postgres
  - python migrate.py
install: pip install -r requirements.txt
script: nosetests tests --with-coverage --cover-package=app && coverage report
after_success: coveralls